# This one only has the database, so we can run dev-mode on the local machine
version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ploxnotes
      - POSTGRES_PASSWORD=postgres
    ports:
    - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
volumes:
  db:
