# Here we expose the ports so we can connect from our dev instance on our local machine
version: '3.8'
services:
  db:
    extends:
      file: docker-compose.yml
      service: db
    ports:
      - '5432:5432'
volumes:
  db:
