version: '3.8'
services:
  web:
    build: .
    ports:
      - '8088:8080'
    restart: always
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ploxnotes
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
volumes:
  db:
    # what was driver? Can it be removed?
    driver: local
