import type { DummyRuleMap } from "oxlint"
import { defineConfig } from "oxlint"

export default defineConfig({
  plugins: ["typescript", "react", "nextjs"],
  // rules without a native oxlint implementation run through these ESLint-compatible JS plugins
  jsPlugins: ["@eslint-react/eslint-plugin", "eslint-plugin-no-only-tests"],
  // every rule is listed explicitly below, mirroring the ESLint presets we used before
  categories: {
    correctness: "off",
  },
  options: {
    typeAware: true,
    maxWarnings: 0,
    reportUnusedDisableDirectives: "error",
    respectEslintDisableDirectives: false,
  },
  env: {
    builtin: true,
  },
  settings: {
    "react-x": {
      version: "detect",
      importSource: "react",
      polymorphicPropName: "as",
    },
  },
  ignorePatterns: [".next", "dist", "next-env.d.ts"],
  rules: {
    ...eslintRecommended(),
    ...typescriptStrictTypeChecked(),
    ...eslintReactRecommendedTypeChecked(),
    ...nextRecommended(),

    // turn on plugin rules
    "no-only-tests/no-only-tests": "error",

    // activate extra rules:
    "typescript/prefer-nullish-coalescing": [
      "error",
      {
        // we want || for boolean logic and ?? for missing data.
        // Ignoring mixed logical expressions makes this rule ignore most boolean logic, so thats nice.
        ignoreMixedLogicalExpressions: true,
      },
    ],
    eqeqeq: ["error", "smart"],
    "no-restricted-globals": [
      "error",
      // call them explicitly with `window.close` instead of just `close`. This is to prevent accidental calls to these functions.
      "alert",
      "blur",
      "close",
      "confirm",
      "event",
      "focus",
      "open",
      "scroll",
      "scrollBy",
      "scrollTo",
      "stop",
    ],
    curly: "error",
    "typescript/strict-boolean-expressions": ["error", { allowNullableBoolean: true }],
    "typescript/prefer-enum-initializers": "error",
    "react/jsx-curly-brace-presence": ["error", { propElementValues: "always" }],

    // change config of activated rules
    "no-unused-vars": [
      "error",
      {
        args: "none",
        caughtErrors: "all",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        ignoreRestSiblings: true,
        fix: { imports: "fix", variables: "suggestion" },
      },
    ],
    "typescript/no-confusing-void-expression": [
      "error",
      {
        // having this active is too verbose
        ignoreArrowShorthand: true,
      },
    ],
    "typescript/no-misused-promises": [
      "error",
      {
        checksVoidReturn: {
          arguments: false,
          attributes: false,
          returns: false,
        },
      },
    ],

    // turn off unwanted rules:
    // oxlint JS plugins get no type information, so this type-aware rule crashes.
    // typescript/strict-boolean-expressions covers most of it (e.g. `count && <X />`).
    "@eslint-react/no-leaked-conditional-rendering": "off",
  },
  overrides: [
    // TypeScript already checks these, same as typescript-eslint's eslint-recommended config
    {
      files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
      rules: {
        "constructor-super": "off",
        "getter-return": "off",
        "no-class-assign": "off",
        "no-const-assign": "off",
        "no-dupe-class-members": "off",
        "no-dupe-keys": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-new-native-nonconstructor": "off",
        "no-obj-calls": "off",
        "no-redeclare": "off",
        "no-setter-return": "off",
        "no-this-before-super": "off",
        "no-undef": "off",
        "no-unreachable": "off",
        "no-unsafe-negation": "off",
        "no-var": "error",
        "no-with": "off",
        "prefer-const": "error",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
      },
    },
  ],
})

// @next/eslint-plugin-next's `recommended`
function nextRecommended(): DummyRuleMap {
  return {
    "nextjs/google-font-display": "warn",
    "nextjs/google-font-preconnect": "warn",
    "nextjs/next-script-for-ga": "warn",
    "nextjs/no-async-client-component": "warn",
    "nextjs/no-before-interactive-script-outside-document": "warn",
    "nextjs/no-css-tags": "warn",
    "nextjs/no-head-element": "warn",
    "nextjs/no-html-link-for-pages": "warn",
    "nextjs/no-img-element": "warn",
    "nextjs/no-page-custom-font": "warn",
    "nextjs/no-styled-jsx-in-document": "warn",
    "nextjs/no-sync-scripts": "warn",
    "nextjs/no-title-in-document-head": "warn",
    "nextjs/no-typos": "warn",
    "nextjs/no-unwanted-polyfillio": "warn",
    "nextjs/inline-script-id": "error",
    "nextjs/no-assign-module-variable": "error",
    "nextjs/no-document-import-in-page": "error",
    "nextjs/no-duplicate-head": "error",
    "nextjs/no-head-import-in-document": "error",
    "nextjs/no-script-component-in-head": "error",
  }
}

function eslintRecommended(): DummyRuleMap {
  return {
    "constructor-super": "error",
    "for-direction": "error",
    "getter-return": "error",
    "no-async-promise-executor": "error",
    "no-case-declarations": "error",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": "error",
    "no-const-assign": "error",
    "no-constant-binary-expression": "error",
    "no-constant-condition": "error",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-delete-var": "error",
    "no-dupe-class-members": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": "error",
    "no-empty-character-class": "error",
    "no-empty-pattern": "error",
    "no-empty-static-block": "error",
    "no-ex-assign": "error",
    "no-extra-boolean-cast": "error",
    "no-fallthrough": "error",
    "no-func-assign": "error",
    "no-global-assign": "error",
    "no-import-assign": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-loss-of-precision": "error",
    "no-misleading-character-class": "error",
    "no-new-native-nonconstructor": "error",
    "no-nonoctal-decimal-escape": "error",
    "no-obj-calls": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": "error",
    "no-regex-spaces": "error",
    "no-self-assign": "error",
    "no-setter-return": "error",
    "no-shadow-restricted-names": "error",
    "no-sparse-arrays": "error",
    "no-this-before-super": "error",
    "no-unassigned-vars": "error",
    "no-undef": "error",
    "no-unexpected-multiline": "error",
    "no-unreachable": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": "error",
    "no-unused-labels": "error",
    "no-unused-private-class-members": "error",
    "no-useless-assignment": "error",
    "no-useless-backreference": "error",
    "no-useless-catch": "error",
    "no-useless-escape": "error",
    "no-with": "error",
    "preserve-caught-error": "error",
    "require-yield": "error",
    "use-isnan": "error",
    "valid-typeof": "error",
  }
}

// typescript-eslint's `strictTypeChecked`, minus the rules we turned off:
// no-non-null-assertion, restrict-template-expressions, no-unsafe-enum-comparison,
// no-unnecessary-boolean-literal-compare, no-deprecated, restrict-plus-operands, no-invalid-void-type
// and no-explicit-any + no-unsafe-member-access/assignment/argument/return (these rules are perfect for
// small simply projects that can avoid `any` type. But not for this project.)
function typescriptStrictTypeChecked(): DummyRuleMap {
  return {
    "no-array-constructor": "error",
    "no-unused-expressions": "error",
    "no-useless-constructor": "error",
    "typescript/await-thenable": "error",
    "typescript/ban-ts-comment": ["error", { minimumDescriptionLength: 10 }],
    "typescript/no-array-delete": "error",
    "typescript/no-base-to-string": "error",
    "typescript/no-duplicate-enum-values": "error",
    "typescript/no-duplicate-type-constituents": "error",
    "typescript/no-dynamic-delete": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-extra-non-null-assertion": "error",
    "typescript/no-extraneous-class": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-for-in-array": "error",
    "typescript/no-implied-eval": "error",
    "typescript/no-meaningless-void-operator": "error",
    "typescript/no-misused-new": "error",
    "typescript/no-misused-spread": "error",
    "typescript/no-mixed-enums": "error",
    "typescript/no-namespace": "error",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-non-null-asserted-optional-chain": "error",
    "typescript/no-redundant-type-constituents": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-this-alias": "error",
    "typescript/no-unnecessary-condition": "error",
    "typescript/no-unnecessary-template-expression": "error",
    "typescript/no-unnecessary-type-arguments": "error",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unnecessary-type-conversion": "error",
    "typescript/no-unnecessary-type-parameters": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-declaration-merging": "error",
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-unsafe-unary-minus": "error",
    "typescript/no-useless-default-assignment": "error",
    "typescript/no-wrapper-object-types": "error",
    "typescript/only-throw-error": "error",
    "typescript/prefer-as-const": "error",
    "typescript/prefer-literal-enum-member": "error",
    "typescript/prefer-namespace-keyword": "error",
    "typescript/prefer-promise-reject-errors": "error",
    "typescript/prefer-reduce-type-parameter": "error",
    "typescript/prefer-return-this-type": "error",
    "typescript/related-getter-setter-pairs": "error",
    "typescript/require-await": "error",
    "typescript/return-await": ["error", "error-handling-correctness-only"],
    "typescript/triple-slash-reference": "error",
    "typescript/unbound-method": "error",
    "typescript/unified-signatures": "error",
    "typescript/use-unknown-in-catch-callback-variable": "error",
  }
}

// @eslint-react's `recommended-type-checked`, minus no-array-index-key
// (small static lists where index-as-key is fine)
function eslintReactRecommendedTypeChecked(): DummyRuleMap {
  return {
    "@eslint-react/error-boundaries": "error",
    "@eslint-react/exhaustive-deps": "warn",
    "@eslint-react/no-access-state-in-setstate": "error",
    "@eslint-react/no-children-count": "warn",
    "@eslint-react/no-children-for-each": "warn",
    "@eslint-react/no-children-map": "warn",
    "@eslint-react/no-children-only": "warn",
    "@eslint-react/no-children-to-array": "warn",
    "@eslint-react/no-clone-element": "warn",
    "@eslint-react/no-component-will-mount": "error",
    "@eslint-react/no-component-will-receive-props": "error",
    "@eslint-react/no-component-will-update": "error",
    "@eslint-react/no-context-provider": "warn",
    "@eslint-react/no-create-ref": "error",
    "@eslint-react/no-direct-mutation-state": "error",
    "@eslint-react/no-forward-ref": "warn",
    "@eslint-react/no-missing-key": "error",
    "@eslint-react/no-nested-component-definitions": "error",
    "@eslint-react/no-nested-lazy-component-declarations": "error",
    "@eslint-react/no-set-state-in-component-did-mount": "warn",
    "@eslint-react/no-set-state-in-component-did-update": "warn",
    "@eslint-react/no-set-state-in-component-will-update": "warn",
    "@eslint-react/no-unnecessary-use-prefix": "warn",
    "@eslint-react/no-unsafe-component-will-mount": "warn",
    "@eslint-react/no-unsafe-component-will-receive-props": "warn",
    "@eslint-react/no-unsafe-component-will-update": "warn",
    "@eslint-react/no-unused-class-component-members": "warn",
    "@eslint-react/no-use-context": "warn",
    "@eslint-react/purity": "warn",
    "@eslint-react/rules-of-hooks": "error",
    "@eslint-react/set-state-in-effect": "warn",
    "@eslint-react/set-state-in-render": "error",
    "@eslint-react/static-components": "error",
    "@eslint-react/unsupported-syntax": "error",
    "@eslint-react/use-memo": "error",
    "@eslint-react/use-state": "warn",
    "@eslint-react/jsx-no-children-prop": "warn",
    "@eslint-react/jsx-no-children-prop-with-children": "error",
    "@eslint-react/jsx-no-comment-textnodes": "warn",
    "@eslint-react/jsx-no-key-after-spread": "error",
    "@eslint-react/jsx-no-leaked-dollar": "warn",
    "@eslint-react/jsx-no-leaked-semicolon": "warn",
    "@eslint-react/jsx-no-namespace": "error",
    "@eslint-react/rsc-function-definition": "error",
    "@eslint-react/dom-no-dangerously-set-innerhtml": "warn",
    "@eslint-react/dom-no-dangerously-set-innerhtml-with-children": "error",
    "@eslint-react/dom-no-find-dom-node": "error",
    "@eslint-react/dom-no-flush-sync": "error",
    "@eslint-react/dom-no-hydrate": "error",
    "@eslint-react/dom-no-render": "error",
    "@eslint-react/dom-no-render-return-value": "error",
    "@eslint-react/dom-no-script-url": "warn",
    "@eslint-react/dom-no-unsafe-iframe-sandbox": "warn",
    "@eslint-react/dom-no-use-form-state": "error",
    "@eslint-react/dom-no-void-elements-with-children": "error",
    "@eslint-react/web-api-no-leaked-event-listener": "warn",
    "@eslint-react/web-api-no-leaked-fetch": "warn",
    "@eslint-react/web-api-no-leaked-intersection-observer": "warn",
    "@eslint-react/web-api-no-leaked-interval": "warn",
    "@eslint-react/web-api-no-leaked-resize-observer": "warn",
    "@eslint-react/web-api-no-leaked-timeout": "warn",
    "@eslint-react/naming-convention-context-name": "warn",
    "@eslint-react/naming-convention-id-name": "warn",
    "@eslint-react/naming-convention-ref-name": "warn",
  }
}
